services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - RESOURCE_CONNECTION=https://static.wongnai.com/devinterview/covid-cases.json
      - GIN_MODE=release